//Просто так.
GET http://localhost:8088/
Accept: application/json

###

//Создание пользователя
POST http://localhost:8088/create
Content-Type: application/json

{
"name": "Иван",
"age": "23"
}

###

//Создание пользователя
POST http://localhost:8088/create
Content-Type: application/json

{
  "name": "Фёдор",

  "age": "29",
  "friends": []
}

###

//Создание пользователя
POST http://localhost:8088/create
Content-Type: application/json

{
  "name": "Сергей",
  "age": "45"
}

###

//Создание пользователя
POST http://localhost:8088/create
Content-Type: application/json

{
  "name": "Олег",
  "age": "43"
}

###

//Создание друзей
POST http://localhost:8088/make_friends
Content-Type: application/json

{"source_id": "1","target_id": "2"}

###

//Создание друзей
POST http://localhost:8088/make_friends
Content-Type: application/json

{"source_id": "1","target_id": "3"}

###

//Создание друзей
POST http://localhost:8088/make_friends
Content-Type: application/json

{"source_id": "1","target_id": "4"}

###

//Создание друзей
POST http://localhost:8088/make_friends
Content-Type: application/json

{"source_id": "1","target_id": "3"}

###

//Создание друзей
POST http://localhost:8088/make_friends
Content-Type: application/json

{"source_id": "4","target_id": "3"}

###

//Создание друзей
POST http://localhost:8088/make_friends
Content-Type: application/json

{"source_id": "2","target_id": "4"}

###

//Получение друзей
GET http://localhost:8088/friends/1
Accept: application/json

###


//Получение всех пользоватлей
GET http://localhost:8088/get_users
Accept: application/json

###

//Удаление пользователя
DELETE http://localhost:8088/user
Content-Type: application/json

{"target_id": "4"}

###

//Получение всех пользоватлей
GET http://localhost:8088/get_users
Accept: application/json

###

//Изминение возраста
PUT http://localhost:8088/user/1
Content-Type: application/json

{"new age": "78"}
